// ***************************************************************************
// ATTENTION: do not edit this file directly, edit files utils/ipfix_names.*
// ***************************************************************************


#include <string.h>
#include <stdio.h>
#include "ipfix_names.h"
#include "ipfix.h"


struct IpfixIDs
{
	uint16_t typeid;
	uint16_t length;
	char* text;
};

struct ipfix_identifier ipfixids[] = {
 { IPFIX_TYPEID_ipVersion, IPFIX_LENGTH_ipVersion, "ipVersion" },
 { IPFIX_TYPEID_sourceIPv4Address, IPFIX_LENGTH_sourceIPv4Address, "sourceIPv4Address" },
 { IPFIX_TYPEID_sourceIPv6Address, IPFIX_LENGTH_sourceIPv6Address, "sourceIPv6Address" },
 { IPFIX_TYPEID_sourceIPv4Mask, IPFIX_LENGTH_sourceIPv4Mask, "sourceIPv4Mask" },
 { IPFIX_TYPEID_sourceIPv6Mask, IPFIX_LENGTH_sourceIPv6Mask, "sourceIPv6Mask" },
 { IPFIX_TYPEID_sourceIPv4Prefix, IPFIX_LENGTH_sourceIPv4Prefix, "sourceIPv4Prefix" },
 { IPFIX_TYPEID_destinationIPv4Address, IPFIX_LENGTH_destinationIPv4Address, "destinationIPv4Address" },
 { IPFIX_TYPEID_destinationIPv6Address, IPFIX_LENGTH_destinationIPv6Address, "destinationIPv6Address" },
 { IPFIX_TYPEID_destinationIPv4Mask, IPFIX_LENGTH_destinationIPv4Mask, "destinationIPv4Mask" },
 { IPFIX_TYPEID_destinationIPv6Mask, IPFIX_LENGTH_destinationIPv6Mask, "destinationIPv6Mask" },
 { IPFIX_TYPEID_destinationIPv4Prefix, IPFIX_LENGTH_destinationIPv4Prefix, "destinationIPv4Prefix" },
 { IPFIX_TYPEID_classOfServiceIPv4, IPFIX_LENGTH_classOfServiceIPv4, "classOfServiceIPv4" },
 { IPFIX_TYPEID_classOfServiceV6, IPFIX_LENGTH_classOfServiceV6, "classOfServiceV6" },
 { IPFIX_TYPEID_flowLabelV6, IPFIX_LENGTH_flowLabelV6, "flowLabelV6" },
 { IPFIX_TYPEID_identificationV4, IPFIX_LENGTH_identificationV4, "identificationV4" },
 { IPFIX_TYPEID_protocolIdentifier, IPFIX_LENGTH_protocolIdentifier, "protocolIdentifier" },
 { IPFIX_TYPEID_sourceTransportPort, IPFIX_LENGTH_sourceTransportPort, "sourceTransportPort" },
 { IPFIX_TYPEID_destinationTransportPort, IPFIX_LENGTH_destinationTransportPort, "destinationTransportPort" },
 { IPFIX_TYPEID_icmpTypeCode, IPFIX_LENGTH_icmpTypeCode, "icmpTypeCode" },
 { IPFIX_TYPEID_igmpType, IPFIX_LENGTH_igmpType, "igmpType" },
 { IPFIX_TYPEID_sourceMacAddress, IPFIX_LENGTH_sourceMacAddress, "sourceMacAddress" },
 { IPFIX_TYPEID_mplsLabelStackEntry1, IPFIX_LENGTH_mplsLabelStackEntry1, "mplsLabelStackEntry1" },
 { IPFIX_TYPEID_mplsLabelStackEntry2, IPFIX_LENGTH_mplsLabelStackEntry2, "mplsLabelStackEntry2" },
 { IPFIX_TYPEID_mplsLabelStackEntry3, IPFIX_LENGTH_mplsLabelStackEntry3, "mplsLabelStackEntry3" },
 { IPFIX_TYPEID_mplsLabelStackEntry4, IPFIX_LENGTH_mplsLabelStackEntry4, "mplsLabelStackEntry4" },
 { IPFIX_TYPEID_mplsLabelStackEntry5, IPFIX_LENGTH_mplsLabelStackEntry5, "mplsLabelStackEntry5" },
 { IPFIX_TYPEID_mplsLabelStackEntry6, IPFIX_LENGTH_mplsLabelStackEntry6, "mplsLabelStackEntry6" },
 { IPFIX_TYPEID_mplsLabelStackEntry7, IPFIX_LENGTH_mplsLabelStackEntry7, "mplsLabelStackEntry7" },
 { IPFIX_TYPEID_mplsLabelStackEntry8, IPFIX_LENGTH_mplsLabelStackEntry8, "mplsLabelStackEntry8" },
 { IPFIX_TYPEID_mplsLabelStackEntry9, IPFIX_LENGTH_mplsLabelStackEntry9, "mplsLabelStackEntry9" },
 { IPFIX_TYPEID_mplsLabelStackEntry10, IPFIX_LENGTH_mplsLabelStackEntry10, "mplsLabelStackEntry10" },
 { IPFIX_TYPEID_ipNextHopIPv4Address, IPFIX_LENGTH_ipNextHopIPv4Address, "ipNextHopIPv4Address" },
 { IPFIX_TYPEID_ipNextHopIPv6Address, IPFIX_LENGTH_ipNextHopIPv6Address, "ipNextHopIPv6Address" },
 { IPFIX_TYPEID_ingressInterface, IPFIX_LENGTH_ingressInterface, "ingressInterface" },
 { IPFIX_TYPEID_egressInterface, IPFIX_LENGTH_egressInterface, "egressInterface" },
 { IPFIX_TYPEID_ipNextHopAsNumber, IPFIX_LENGTH_ipNextHopAsNumber, "ipNextHopAsNumber" },
 { IPFIX_TYPEID_bgpSourceAsNumber, IPFIX_LENGTH_bgpSourceAsNumber, "bgpSourceAsNumber" },
 { IPFIX_TYPEID_bgpDestinationAsNumber, IPFIX_LENGTH_bgpDestinationAsNumber, "bgpDestinationAsNumber" },
 { IPFIX_TYPEID_bgpNextHopAsNumber, IPFIX_LENGTH_bgpNextHopAsNumber, "bgpNextHopAsNumber" },
 { IPFIX_TYPEID_bgpNextHopIPv4Address, IPFIX_LENGTH_bgpNextHopIPv4Address, "bgpNextHopIPv4Address" },
 { IPFIX_TYPEID_bgpNextHopIPv6Address, IPFIX_LENGTH_bgpNextHopIPv6Address, "bgpNextHopIPv6Address" },
 { IPFIX_TYPEID_mplsTopLabelType, IPFIX_LENGTH_mplsTopLabelType, "mplsTopLabelType" },
 { IPFIX_TYPEID_mplsTopLabelIPv4Address, IPFIX_LENGTH_mplsTopLabelIPv4Address, "mplsTopLabelIPv4Address" },
 { IPFIX_TYPEID_mplsTopLabelIPv6Address, IPFIX_LENGTH_mplsTopLabelIPv6Address, "mplsTopLabelIPv6Address" },
 { IPFIX_TYPEID_exporterIPv4Address, IPFIX_LENGTH_exporterIPv4Address, "exporterIPv4Address" },
 { IPFIX_TYPEID_exporterIPv6Address, IPFIX_LENGTH_exporterIPv6Address, "exporterIPv6Address" },
 { IPFIX_TYPEID_minPacketLength, IPFIX_LENGTH_minPacketLength, "minPacketLength" },
 { IPFIX_TYPEID_maxPacketLength, IPFIX_LENGTH_maxPacketLength, "maxPacketLength" },
 { IPFIX_TYPEID_minimumTTL, IPFIX_LENGTH_minimumTTL, "minimumTTL" },
 { IPFIX_TYPEID_maximumTTL, IPFIX_LENGTH_maximumTTL, "maximumTTL" },
 { IPFIX_TYPEID_ipv6ExtensionHeaders, IPFIX_LENGTH_ipv6ExtensionHeaders, "ipv6ExtensionHeaders" },
 { IPFIX_TYPEID_tcpControlBits, IPFIX_LENGTH_tcpControlBits, "tcpControlBits" },
 { IPFIX_TYPEID_flowStartSysUpTime, IPFIX_LENGTH_flowStartSysUpTime, "flowStartSysUpTime" },
 { IPFIX_TYPEID_flowEndSysUpTime, IPFIX_LENGTH_flowEndSysUpTime, "flowEndSysUpTime" },
 { IPFIX_TYPEID_flowStartSeconds, IPFIX_LENGTH_flowStartSeconds, "flowStartSeconds" },
 { IPFIX_TYPEID_flowEndSeconds, IPFIX_LENGTH_flowEndSeconds, "flowEndSeconds" },
 { IPFIX_TYPEID_flowStartMilliSeconds, IPFIX_LENGTH_flowStartMilliSeconds, "flowStartMilliSeconds" },
 { IPFIX_TYPEID_flowEndMilliSeconds, IPFIX_LENGTH_flowEndMilliSeconds, "flowEndMilliSeconds" },
 { IPFIX_TYPEID_flowStartMicroSeconds, IPFIX_LENGTH_flowStartMicroSeconds, "flowStartMicroSeconds" },
 { IPFIX_TYPEID_flowEndMicroSeconds, IPFIX_LENGTH_flowEndMicroSeconds, "flowEndMicroSeconds" },
 { IPFIX_TYPEID_flowStartNanoSeconds, IPFIX_LENGTH_flowStartNanoSeconds, "flowStartNanoSeconds" },
 { IPFIX_TYPEID_flowEndNanoSeconds, IPFIX_LENGTH_flowEndNanoSeconds, "flowEndNanoSeconds" },
 { IPFIX_TYPEID_flowActiveTimeOut, IPFIX_LENGTH_flowActiveTimeOut, "flowActiveTimeOut" },
 { IPFIX_TYPEID_flowInactiveTimeout, IPFIX_LENGTH_flowInactiveTimeout, "flowInactiveTimeout" },
 { IPFIX_TYPEID_flowEndReason, IPFIX_LENGTH_flowEndReason, "flowEndReason" },
 { IPFIX_TYPEID_octetDeltaCount, IPFIX_LENGTH_octetDeltaCount, "octetDeltaCount" },
 { IPFIX_TYPEID_postOctetDeltaCount, IPFIX_LENGTH_postOctetDeltaCount, "postOctetDeltaCount" },
 { IPFIX_TYPEID_octetTotalCount, IPFIX_LENGTH_octetTotalCount, "octetTotalCount" },
 { IPFIX_TYPEID_packetDeltaCount, IPFIX_LENGTH_packetDeltaCount, "packetDeltaCount" },
 { IPFIX_TYPEID_postPacketDeltaCount, IPFIX_LENGTH_postPacketDeltaCount, "postPacketDeltaCount" },
 { IPFIX_TYPEID_packetTotalCount, IPFIX_LENGTH_packetTotalCount, "packetTotalCount" },
 { IPFIX_TYPEID_droppedOctetDeltaCount, IPFIX_LENGTH_droppedOctetDeltaCount, "droppedOctetDeltaCount" },
 { IPFIX_TYPEID_droppedOctetTotalCount, IPFIX_LENGTH_droppedOctetTotalCount, "droppedOctetTotalCount" },
 { IPFIX_TYPEID_droppedPacketDeltaCount, IPFIX_LENGTH_droppedPacketDeltaCount, "droppedPacketDeltaCount" },
 { IPFIX_TYPEID_droppedPacketTotalCount, IPFIX_LENGTH_droppedPacketTotalCount, "droppedPacketTotalCount" },
 { IPFIX_TYPEID_postMCastPacketDeltaCount, IPFIX_LENGTH_postMCastPacketDeltaCount, "postMCastPacketDeltaCount" },
 { IPFIX_TYPEID_postMCastOctetDeltaCount, IPFIX_LENGTH_postMCastOctetDeltaCount, "postMCastOctetDeltaCount" },
 { IPFIX_TYPEID_observedFlowTotalCount, IPFIX_LENGTH_observedFlowTotalCount, "observedFlowTotalCount" },
 { IPFIX_TYPEID_exportedOctetTotalCount, IPFIX_LENGTH_exportedOctetTotalCount, "exportedOctetTotalCount" },
 { IPFIX_TYPEID_exportedMessageTotalCount, IPFIX_LENGTH_exportedMessageTotalCount, "exportedMessageTotalCount" },
 { IPFIX_TYPEID_exportedFlowTotalCount, IPFIX_LENGTH_exportedFlowTotalCount, "exportedFlowTotalCount" },
 { IPFIX_TYPEID_fragmentOffsetIPv4, IPFIX_LENGTH_fragmentOffsetIPv4, "fragmentOffsetIPv4" },
 { IPFIX_TYPEID_ipTimeToLive, IPFIX_LENGTH_ipTimeToLive, "ipTimeToLive" },
 { IPFIX_TYPEID_udpSourcePort, IPFIX_LENGTH_udpSourcePort, "udpSourcePort" },
 { IPFIX_TYPEID_udpDestinationPort, IPFIX_LENGTH_udpDestinationPort, "udpDestinationPort" },
 { IPFIX_TYPEID_tcpSourcePort, IPFIX_LENGTH_tcpSourcePort, "tcpSourcePort" },
 { IPFIX_TYPEID_tcpDestinationPort, IPFIX_LENGTH_tcpDestinationPort, "tcpDestinationPort" },
 { IPFIX_TYPEID_tcpSequenceNumber, IPFIX_LENGTH_tcpSequenceNumber, "tcpSequenceNumber" },
 { IPFIX_TYPEID_tcpAcknowledgementNumber, IPFIX_LENGTH_tcpAcknowledgementNumber, "tcpAcknowledgementNumber" },
 { IPFIX_TYPEID_tcpWindowSize, IPFIX_LENGTH_tcpWindowSize, "tcpWindowSize" },
 { IPFIX_TYPEID_tcpUrgentPointer, IPFIX_LENGTH_tcpUrgentPointer, "tcpUrgentPointer" },
 { IPFIX_TYPEID_totalLengthIPv4, IPFIX_LENGTH_totalLengthIPv4, "totalLengthIPv4" },
 { IPFIX_ETYPEID_frontPayload, 0, "frontPayload" },
 { IPFIX_ETYPEID_frontPayloadLen, IPFIX_ELENGTH_frontPayloadLen, "frontPayloadLen" },
 { IPFIX_ETYPEID_maxPacketGap, IPFIX_ELENGTH_maxPacketGap, "maxPacketGap" },
 { IPFIX_ETYPEID_frontPayloadPktCount, IPFIX_ELENGTH_frontPayloadPktCount, "frontPayloadPktCount" },
 { IPFIX_ETYPEID_dpaFlowCount, IPFIX_ELENGTH_dpaFlowCount, "dpaFlowCount" },
 { IPFIX_ETYPEID_dpaForcedExport, IPFIX_ELENGTH_dpaForcedExport, "dpaForcedExport" },
 { IPFIX_ETYPEID_revFlowStartSeconds, IPFIX_ELENGTH_revFlowStartSeconds, "revFlowStartSeconds" },
 { IPFIX_ETYPEID_revFlowStartMilliSeconds, IPFIX_ELENGTH_revFlowStartMilliSeconds, "revFlowStartMilliSeconds" },
 { IPFIX_ETYPEID_revFlowStartNanoSeconds, IPFIX_ELENGTH_revFlowStartNanoSeconds, "revFlowStartNanoSeconds" },
 { IPFIX_ETYPEID_revFlowEndSeconds, IPFIX_ELENGTH_revFlowEndSeconds, "revFlowEndSeconds" },
 { IPFIX_ETYPEID_revFlowEndMilliSeconds, IPFIX_ELENGTH_revFlowEndMilliSeconds, "revFlowEndMilliSeconds" },
 { IPFIX_ETYPEID_revFlowEndNanoSeconds, IPFIX_ELENGTH_revFlowEndNanoSeconds, "revFlowEndNanoSeconds" },
 { IPFIX_ETYPEID_revOctetDeltaCount, IPFIX_ELENGTH_revOctetDeltaCount, "revOctetDeltaCount" },
 { IPFIX_ETYPEID_revPacketDeltaCount, IPFIX_ELENGTH_revPacketDeltaCount, "revPacketDeltaCount" },
 { IPFIX_ETYPEID_revTcpControlBits, IPFIX_ELENGTH_revTcpControlBits, "revTcpControlBits" },
 { IPFIX_ETYPEID_revFrontPayload, 0, "revFrontPayload" },
 { IPFIX_ETYPEID_revFrontPayloadLen, IPFIX_ELENGTH_revFrontPayloadLen, "revFrontPayloadLen" },
 { IPFIX_ETYPEID_revFrontPayloadPktCount, IPFIX_ELENGTH_revFrontPayloadPktCount, "revFrontPayloadPktCount" },
 { IPFIX_ETYPEID_revMaxPacketGap, IPFIX_ELENGTH_revMaxPacketGap, "revMaxPacketGap" }
};


/* lookup a certain ipfix ID into its name */
const struct ipfix_identifier * ipfix_id_lookup(int n)
{
	uint32_t i;
	for (i=0; i<sizeof(ipfixids)/sizeof(struct ipfix_identifier); i++) {
		if (ipfixids[i].id==n) {
			return &ipfixids[i];
		}
	}
	return NULL;
}

/*
 lookup an ipfix name into its ID
 int because we need -1 for "not found"
 */
int ipfix_name_lookup(const char *name)
{
	const struct ipfix_identifier *tmp = 0;
	uint32_t i;

	for (i=0; i<sizeof(ipfixids)/sizeof(struct ipfix_identifier); i++) {
		if (strcasecmp(name, ipfixids[i].name)==0) {
			tmp = &ipfixids[i];
		}
	}
	if (!tmp) {
		/* not found */
		return -1;
	}

	return (int)tmp->id;
}

#ifdef __cplusplus
}
#endif
