# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.hostname = "vermont"
  config.vm.box = "trusty_amd"
  config.vm.box_url = "https://cloud-images.ubuntu.com/vagrant/trusty/current/trusty-server-cloudimg-amd64-vagrant-disk1.box"
  config.vm.network "private_network", ip: "192.168.50.4"
  config.vm.synced_folder  "../",  "/vermont"

  config.vm.provision "shell", inline: "apt-get install python3"   # For ansible to function
  config.vm.provision "ansible" do |ansible|
    ansible.playbook = "playbook.yml"
    ansible.extra_vars = {  ansible_python_interpreter: "/usr/bin/python3" }
  end
end
